remote_theme: "mmistakes/minimal-mistakes"

title: "Nathan Crowder"
name: "Nathan Crowder"
description: "Data Professional"

url: "https://crowder-data.github.io"
baseurl: ""

plugins:
  - jekyll-include-cache
