remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "aqua"

title: "Nathan Crowder"
name: "Nathan Crowder"
description: "Data Professional"

titles_from_headings:
  enabled: false

url: "https://crowder-data.github.io"
baseurl: ""

plugins:
  - jekyll-include-cache
